### ISSUE TITLE
Falha na geração do boleto

### ISSUE THREAD

**Issue by hlegius** [gabrielrcouto/php-itaucripto#1]
Olá,

Implementei sua classe conforme manda o manual do Itaú ShopLine e suas recomendações, porém estou recebendo um erro já no ambiente do Itaú:

http://cl.ly/image/2M022x2a1e2A

Ao que pesquisei na Internet, outras pessoas que tentaram utilizar sua classe também estão com o mesmo problema. Acredito que o Itaú tenha atualizado a velha interface deles, não?

Obrigado!

**Comment by fabiolnm** [comment]
Passei por estes problemas recentemente, e os diagnósticos foram

* WLAO-032: o endereço no máximo 41 caracteres. 
* WLAO-033: o nome do cliente tinha que ter no máximo 30 caracteres.

**Comment by gabrielrcouto** [comment]
Valeu @fabiolnm! Acho que vai ser até uma boa então adicionarmos na função da lib um crop da string para evitar que dê erros!

**Comment by diegorribeiro** [comment]
@gabrielrcouto será uma boa o crop sim, alguns erros que andei observando são exatamente nas strings enviadas ao geraDados();

**Comment by vitorSC** [comment]
Bom dia, 

Está retornado erro 9 - Contato o atendimento CESE, mas meu código está ok a princípio:

$oIntegracaoItauShopLine = new IntegracaoItauShopLine;
$oIntegracaoItauShopLine->setCodigoEmpresa('X12334412DSF2334455121232');
$oIntegracaoItauShopLine->setNumeroPedido('123');
$oIntegracaoItauShopLine->setValor('10,00');
$oIntegracaoItauShopLine->setObservacao('');
$oIntegracaoItauShopLine->setChaveAcesso('233DFFGBD4332X');
$oIntegracaoItauShopLine->setNomeSacado('Vitor');
$oIntegracaoItauShopLine->setCodigoInscricaoSacado('01');
$oIntegracaoItauShopLine->setNumeroInscricaoSacado('9999999999');
$oIntegracaoItauShopLine->setEnderecoSacado('Rua teste');
$oIntegracaoItauShopLine->setBairroSacado('Centro');
$oIntegracaoItauShopLine->setCepSacado('89180000');
$oIntegracaoItauShopLine->setCidadeSacado('Cidade teste');
$oIntegracaoItauShopLine->setEstadoSacado('SC');
$oIntegracaoItauShopLine->setDataVencimento('05112015');
$oIntegracaoItauShopLine->setUrlRetorna('https://www.site.com.br/retornoItau');
$oIntegracaoItauShopLine->setObsAdicional1('');
$oIntegracaoItauShopLine->setObsAdicional2('');
$oIntegracaoItauShopLine->setObsAdicional3('');

$oItauCriptografia = new Itaucripto();

/*
 * Chave enviada no formulário
 */
$chaveCriptografadaRequisicao = $oItauCriptografia->geraDados($oIntegracaoItauShopLine->getCodigoEmpresa(),$oIntegracaoItauShopLine->getNumeroPedido(),$oIntegracaoItauShopLine->getValor(),$oIntegracaoItauShopLine->getObservacao(),$oIntegracaoItauShopLine->getChaveAcesso(),$oIntegracaoItauShopLine->getNomeSacado(),$oIntegracaoItauShopLine->getCodigoInscricaoSacado(),$oIntegracaoItauShopLine->getNumeroInscricaoSacado(),$oIntegracaoItauShopLine->getEnderecoSacado(),$oIntegracaoItauShopLine->getBairroSacado(),$oIntegracaoItauShopLine->getCepSacado(),$oIntegracaoItauShopLine->getCidadeSacado(),$oIntegracaoItauShopLine->getEstadoSacado(),$oIntegracaoItauShopLine->getDataVencimento(),$oIntegracaoItauShopLine->getUrlRetorna(),$oIntegracaoItauShopLine->getObsAdicional1(),$oIntegracaoItauShopLine->getObsAdicional2(),$oIntegracaoItauShopLine->getObsAdicional3());

Saberia o que pode ser?

**Comment by gabrielrcouto** [comment]
@vitorSC infelizmente não sei. Você chegou a descobrir?

**Comment by vitorSC** [comment]
Bom dia,

Eu não consegui via php, acabei instalando o Tomcat e criei um jsp para instanciar o.class que o Itaú disponibiliza, ou seja, criei um serviço para chamar via rest apenas para retornar a chave :(, mas deu tudo certo o problema é a mão de obra apenas para isso.

**Comment by davydcm** [comment]
Oi,

Alguém conseguiu descobrir o motivo do problema: ERRO 9 CONTATE O ATENDIMENTO CESE. ??

Abraços

**Comment by diegorribeiro** [comment]
No meu caso, eu estava enviando dados incorretos pro CRIPTO, faz muito tempo que resolvi essa questão em meu projeto, mas eu estava informando (se não me engano) o valor de forma incorreta,.. eu revisei todos os campos e funcionou;

**Comment by davydcm** [comment]
Valeu, diegorribeiro,

vou dar uma analisada. 

Abraço

**Comment by jpratesmoreira** [comment]
Alguem sabe se a URL de teste esta funcionando, pois acesso e não eh exibido nada.

**Comment by aCidcOde** [comment]
Acabei de ter problemas com o erro 09, e o problema aconteceu porque eu deixei os campos observação e url de retorno em branco ou nulo.

  $boleto_urlRetorna = "https://escritorio.cliente.com/escritorio/resumo";
                $boleto_obsAd1 = "Testes";
                $boleto_obsAd2 = "Teste2";
                $boleto_obsAd3 = "testes3";

Foi alterar isso que já funcionou.

@gabrielrcouto Obrigado pela classe, agilizou muito aqui.
@hlegius eae mano! o/
