### ISSUE TITLE
Variavel public $CHAVE_ITAU

### ISSUE THREAD

**Issue by MarcioMonteNegro** [gabrielrcouto/php-itaucripto#10]
Boa tarde, gostaria de saber que informação devo preencher a variavel public $CHAVE_ITAU = "SEGUNDA12345ITAU".

**Comment by gabrielrcouto** [comment]
Olá @MarcioMonteNegro! 

Faz tempo que não mexo com isso, mas até onde me lembro, ela deve ser mantida assim mesmo, esse valor está dentro da classe Java do Itaú.
