### ISSUE TITLE
Ambiente de testes

### ISSUE THREAD

**Issue by mtxr** [gabrielrcouto/php-itaucripto#13]
Como configuro um ambiente de testes no Itaú para testar a lib? Sei que não é uma dúvida exatamente do projeto, mas não encontrei nada na internet.

Obrigado.

**Comment by gabrielrcouto** [comment]
No PDF da documentação do Shopline (que está nesse mesmo repositório, https://github.com/gabrielrcouto/php-itaucripto/blob/master/documenta%C3%A7%C3%A3o%20Ita%C3%BA/ITAUSHOPLINE_MANUAL_TECNICO_DEZ_11.pdf), na página 5, está explicado sobre como usar o ambiente de testes.
