### ISSUE TITLE
Boleto em Branco

### ISSUE THREAD

**Issue by felipefausto** [gabrielrcouto/php-itaucripto#5]
Eae, galera, beleza?

Então, cara, coloquei tudo certinho aqui na minha loja e ele chega até a tela onde a pessoa escolhe se é boleto ou tranferencia ou débito em conta, porem, quando escolho boleto, ele gera em branco, totalmente em branco. Não sei se pode ser algo do Próprio Itaú (Mesmo porque não consegui contato com eles) ou se coloquei algo de errado no módulo, alguma config. Alguem pode dar um help? :smiley:

**Comment by gabrielrcouto** [comment]
Fala Felipe,

Putz, isso nunca aconteceu comigo. Você já conseguiu resolver? Meu chute é que é coisa do Itaú.

Abraços,
Gabriel

**Comment by diegorribeiro** [comment]
Tente realizar os testes enviando o $POST para shopline.asp e não para emissao_teste.asp

no emissão teste a tela fica branca em meus testes, mas no oficial está funcionando normalmente;

**Comment by gabrielrcouto** [comment]
@diegorribeiro você conseguiu resolver?

**Comment by gabrielrcouto** [comment]
Fechada após meses sem resposta.
