### ISSUE TITLE
Valor Limite Boleto

### ISSUE THREAD

**Issue by luuckx2** [gabrielrcouto/php-itaucripto#6]
Fala galera beleeza?
To com um problema, quando gero boletos acima de 1.000,00 o boleto fica em branco e não registra..
abaixo disso ele funciona normal.
Alguém sabe o que pode ser?
Na parte que gera o valor eu to fazendo assim
$value = 1000.00;
$valor = number_format($value, 2, ',', '.'); // return 1.000,00

**Comment by diegorribeiro** [comment]
o valor deve estar como "1000,00" em string

acredito ser isso,
