### ISSUE TITLE
Retorno On-line após a escolha do meio de pagamento

### ISSUE THREAD

**Issue by diegorribeiro** [gabrielrcouto/php-itaucripto#7]
Não estou conseguindo ver o retorno do shopline, alguém tem idéia do que pode ser ?

no teste estou tentando o seguinte:

na área interna do itaú eu estou colocando  URL => https://sitedocliente.com.br

no código php to colocando a $urlRetorna = "/homologacao/cesta/retorno_shopline";

dentro da função retorno coloquei algumas ações para registrar qualquer tipo de retorno, e não está sendo requisitada pelo itaú..

na documentação itaú shopline eles informam que será feita uma concatenação entre as duas URLs e assim será enviado um retorno;

alguém sabe o motivo de não ocorrer o retorno ??

**Comment by gabrielrcouto** [comment]
@diegorribeiro desculpe a demora, infelizmente não passei por esse problema. Você tem alguma novidade?

**Comment by diegorribeiro** [comment]
Cara, foi mal.. foi vacilo meu e do pessoal responsável pelo ssl, o servidor não estava com o certificado no domínio que solicitei.. por isso o itaú não retornava nada.. 

como eu não conseguia retornar, fiz uma consulta em um cron (maior rolê atoa) para ter os dados do pedido realizado.. um trabalho desnecessário, já que estava tudo OK desde o começo e eu fiquei lá quebrando a cabeça confiando nesse "SSL que seria instalado por terceiros",..

Mas valeu, tá tudo ok agora.
