### ISSUE TITLE
Dúvida com php-itaucripto

### ISSUE THREAD

**Issue by quinhone** [gabrielrcouto/php-itaucripto#9]
Eu utilizando a classe PHP, não tem necessidade do uso do java né? Pergunto pq meu servidor é compartilhado e não posso utilizar java nele. Só com a classe itaucripto.php eu já consigo criptografar e chamar o shopline?

**Comment by gabrielrcouto** [comment]
@quinhone Essa biblioteca foi criada exatamente para que não seja necessário utilizar o java ;-)
